kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: phoenix-chat
        image: chat:libcluster #alvises/phoenix-chat-example:libcluster-kube
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: PHOENIX_CHAT_HOST
          value: "localhost"
        - name: ERLANG_COOKIE
          value: "secret"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["elixir"]
        args: [
          "--name",
          "chat@$(MY_POD_IP)",
          "--cookie","$(ERLANG_COOKIE)",
          "--no-halt",
          "-S","mix",
          "phx.server"
        ]
---
kind: Service
apiVersion: v1

metadata:
  name: chat-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: chat
  ports:
    - name: epmd
      port: 4369
---
apiVersion: v1
kind: Service
metadata:
  name: devops-toolkit
spec:
  type: NodePort
  ports:
  - port: 4000
    nodePort: 30003
  selector:
    app: chat
